ALTER TABLE "Participant" ADD COLUMN IF NOT EXISTS "city" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Participant" ADD COLUMN IF NOT EXISTS "church" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Participant" ADD COLUMN IF NOT EXISTS "howHeard" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Participant" ADD COLUMN IF NOT EXISTS "extraInfo" TEXT NOT NULL DEFAULT '';
