-- AlterTable
ALTER TABLE "Participant" ADD COLUMN IF NOT EXISTS "lunchType" TEXT;
ALTER TABLE "Participant" ADD COLUMN IF NOT EXISTS "hasAllergy" BOOLEAN;
ALTER TABLE "Participant" ADD COLUMN IF NOT EXISTS "allergyNote" TEXT NOT NULL DEFAULT '';
